# Generated by Django 6.0.6 on 2026-09-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
