# Generated by Django 6.0.6 on 2026-09-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
